version: '3.1'
services:

  code:
    volumes:
      - ${PWD}/php-override.ini:/usr/local/etc/php/conf.d/php-override.ini
    image: jenkins.paulbunyan.net:5000/php:7.4
    ports:
      - "3000"
      - "3001"
    links:
      - "web:my-website.localhost"
